### ISSUE TITLE
关于BCV数据集中35号数据胆囊

### ISSUE THREAD

**Issue by lzy-whut** [lseventeen/PHTrans#3]
您好，有幸拜读您的论文但我对您论文里报道的实验结果有一个疑问。
BCV数据集中35号数据的胆囊无金标准，那么您论文里胆囊的平均dice80.89是其余11个测试集数据的均值呢，还是包含35号数据的12个测试集数据的均值呢？

**Comment by lseventeen** [comment]
您好！

抱歉，最近使用这个工作参加一个比赛。没及时的回复您。

具体的评估计算方法可见[metrics.py](https://github.com/lseventeen/PHTrans/blob/main/PHTrans/phtrans/inference/metrics.py)。 测试的结果是所有测试数据的均值，即使35号数据的胆囊无金标准，但是还是可以计算的，例如，35号数据中gt没有胆囊，但是错误分割出来了。
