### ISSUE TITLE
BCV 数据集划分

### ISSUE THREAD

**Issue by JasonRichard** [lseventeen/PHTrans#4]
谢谢你的工作，对我很有启发！

论文中是按照18: 12在BCV训练集划分的训练-测试数据吗？
我看dataset_conversion中的处理方式是从训练集30个样本拿出12个做测试，但是训练还是按30个样本进行训练。
文中写到是参考nnformer的划分，nnformer/dataset_json/Synapse.json里面也是这样的。
https://github.com/282857341/nnFormer/issues/4
nnformer中写着参考的是TransUNet的划分

还有一个问题，所有5个fold都跑完了吗？我看只提供了一个model_best.model，是所有fold最好的一个吗？

祝好，

**Comment by lseventeen** [comment]
您好！

抱歉，最近使用这个工作参加一个比赛。没及时的回复您。感谢您对我们的工作有兴趣。

BCV数据集（也称为Synapse）参考的是TransUNet和nnformer的18: 12的划分，具体的case可见[Task017_BeyondCranialVaultAbdominalOrganSegmentation.py](https://github.com/lseventeen/PHTrans/blob/main/PHTrans/phtrans/dataset_conversion/Task017_BeyondCranialVaultAbdominalOrganSegmentation.py)。数据划分文件（splits_final.pkl）提前在这个python文件中写好了。训练时使用fold 0-4 都可以。而model_best.model是nnUNet的特性，训练后保存了两个权重文件，一个是最后一个epoch的权重（model_final_checkpoint.model），另一个是loss最低那个epoch的权重（model_best.model）。事实上，我们测试的结果中两种模型权重的测试结果几乎一致。希望上述回答能解决你的问题。

祝好!
