### ISSUE TITLE
训练时验证集上面的Dice系数比测试时高很多

### ISSUE THREAD

**Issue by PengchengShi1220** [lseventeen/PHTrans#6]
作者你好，我对你提供的代码进行了复现，发现在训练时验证集上面的Dice系数（evaluation metric）比测试时高很多。

检查一遍代码发现你将
https://github.com/lseventeen/PHTrans/blob/937a8d2ce92d2d720abba5abd69680c9d340babe/PHTrans/phtrans/training/PHTransTrainer.py#L774
中的
l = self.run_iteration(self.tr_gen, True)
改成了
l = self.run_iteration(self.tr_gen, True, True)

这个改动造成的结果就是evaluation metric不再只是验证集上的平均Dice系数，而是包含了训练集和验证集所有数据的平均Dice系数。训练集数据在训练过程中会不断拟合，训练集的平均Dice系数一般都会高于验证集的平均Dice系数，造成改动之后的代码在训练时验证集上面的Dice系数比测试时高很多。

想请教一下，你是出于什么样的考虑改动的呢？如果是疏忽，希望能修改这个错误；如果是别的原因，希望你能给出解答，感谢！

**Comment by lseventeen** [comment]
原代码时没有对训练集评估Dice，后期版本对这部分已经补充。这并不影响结果。

**Comment by lseventeen** [comment]
> 作者你好，我对你提供的代码进行了复现，发现在训练时验证集上面的Dice系数（evaluation metric）比测试时高很多。
> 
> 检查一遍代码发现你将
> 
> https://github.com/lseventeen/PHTrans/blob/937a8d2ce92d2d720abba5abd69680c9d340babe/PHTrans/phtrans/training/PHTransTrainer.py#L774
> 
> 
> 中的
> l = self.run_iteration(self.tr_gen, True)
> 改成了
> l = self.run_iteration(self.tr_gen, True, True)
> 这个改动造成的结果就是evaluation metric不再只是验证集上的平均Dice系数，而是包含了训练集和验证集所有数据的平均Dice系数。训练集数据在训练过程中会不断拟合，训练集的平均Dice系数一般都会高于验证集的平均Dice系数，造成改动之后的代码在训练时验证集上面的Dice系数比测试时高很多。
> 
> 想请教一下，你是出于什么样的考虑改动的呢？如果是疏忽，希望能修改这个错误；如果是别的原因，希望你能给出解答，感谢！

原代码时没有对训练集评估Dice，后期版本对这部分已经补充。这并不影响结果。
